version: '3'

services:
  # Django application service
  mydjangoapp:
    image: mydjangoapp:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=BlackHoles@1

  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BlackHoles@1